extraction:
  cpp:
    configure:
      command:
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake -DBUILD_GTEST=OFF -DINSTALL_GTEST=OFF ..
    index:
      build_command:
        - cd _lgtm_build_dir
        - make
  python:
    python_setup:
      version: 3

path_classifiers:
  library:
    - Libraries
